package ir.ac.kntu.kilid.models;

public enum HouseFeature {
    ELEVATOR, BALCONY, STORAGE, SECURITY_GUARD, POOL, SAUNA, JACUZZI, AIR_CONDITIONING, CONFERENCE_HALL, CENTRAL_ANTENNA,
    REMOTE_DOOR, ROOF_GARDEN
}
